// @ts-nocheck — test file, vitest uses esbuild transform
import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('../../utils/logger.js', () => ({
  logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn(), debug: vi.fn() },
}));

// Mock config
vi.mock('../../config.js', () => ({
  config: {
    feishu: {
      appId: 'cli_test_app_id',
      appSecret: 'test_app_secret_32bytes_long_xxx',
      oauth: { redirectUri: 'https://example.com/feishu/oauth/callback', scopes: 'task:task:read task:task:write' },
    },
  },
}));

// Mock feishuClient
const mockRequest = vi.fn();
const mockSendText = vi.fn();
vi.mock('../client.js', () => ({
  feishuClient: {
    raw: { request: (...args: unknown[]) => mockRequest(...args) },
    sendText: (...args: unknown[]) => mockSendText(...args),
  },
}));

// Mock sessionManager
const mockUpsertUserToken = vi.fn();
const mockGetUserToken = vi.fn();
const mockDeleteUserToken = vi.fn();
vi.mock('../../session/manager.js', () => ({
  sessionManager: {
    upsertUserToken: (...args: unknown[]) => mockUpsertUserToken(...args),
    getUserToken: (...args: unknown[]) => mockGetUserToken(...args),
    deleteUserToken: (...args: unknown[]) => mockDeleteUserToken(...args),
  },
}));

import { generateAuthUrl, verifyState, handleOAuthCallback, getValidUserToken, isOAuthConfigured } from '../oauth.js';

beforeEach(() => {
  vi.clearAllMocks();
});

describe('isOAuthConfigured', () => {
  it('should return true when redirectUri is set', () => {
    expect(isOAuthConfigured()).toBe(true);
  });
});

describe('generateAuthUrl', () => {
  it('should return a valid URL with state', () => {
    const url = generateAuthUrl('ou_user123', 'oc_chat456');
    expect(url).toContain('https://open.feishu.cn/open-apis/authen/v1/authorize');
    expect(url).toContain('app_id=cli_test_app_id');
    expect(url).toContain('redirect_uri=');
    expect(url).toContain('state=');
  });

  it('should include scope parameter with task permissions', () => {
    const url = generateAuthUrl('ou_user123', 'oc_chat456');
    const parsed = new URL(url);
    const scope = parsed.searchParams.get('scope');
    expect(scope).toContain('task:task:read');
    expect(scope).toContain('task:task:write');
  });
});

describe('verifyState', () => {
  it('should verify a state generated by generateAuthUrl', () => {
    const url = generateAuthUrl('ou_user123', 'oc_chat456');
    const stateParam = new URL(url).searchParams.get('state')!;
    const payload = verifyState(stateParam);
    expect(payload).toBeDefined();
    expect(payload!.userId).toBe('ou_user123');
    expect(payload!.chatId).toBe('oc_chat456');
  });

  it('should reject invalid state', () => {
    expect(verifyState('invalid')).toBeUndefined();
    expect(verifyState('')).toBeUndefined();
    expect(verifyState('abc.wrong_sig')).toBeUndefined();
  });

  it('should reject tampered state', () => {
    const url = generateAuthUrl('ou_user123', 'oc_chat456');
    const stateParam = new URL(url).searchParams.get('state')!;
    // Tamper with the data part
    const tampered = 'x' + stateParam.slice(1);
    expect(verifyState(tampered)).toBeUndefined();
  });
});

describe('handleOAuthCallback', () => {
  it('should reject invalid state', async () => {
    const result = await handleOAuthCallback('code123', 'invalid_state');
    expect(result).toContain('state 无效');
    expect(mockRequest).not.toHaveBeenCalled();
  });

  it('should exchange code and store token on success', async () => {
    mockRequest.mockResolvedValue({
      code: 0,
      data: {
        access_token: 'u-access-token',
        refresh_token: 'u-refresh-token',
        expires_in: 7200,
        open_id: 'ou_user123',
      },
    });

    const url = generateAuthUrl('ou_user123', 'oc_chat456');
    const state = new URL(url).searchParams.get('state')!;
    const result = await handleOAuthCallback('valid_code', state);

    expect(result).toContain('授权成功');
    expect(mockRequest).toHaveBeenCalledWith(expect.objectContaining({
      method: 'POST',
      url: '/open-apis/authen/v1/oidc/access_token',
      data: { grant_type: 'authorization_code', code: 'valid_code' },
    }));
    expect(mockUpsertUserToken).toHaveBeenCalledWith(
      'ou_user123',
      'u-access-token',
      'u-refresh-token',
      expect.any(Number),
    );
    expect(mockSendText).toHaveBeenCalledWith('oc_chat456', expect.stringContaining('授权成功'));
  });

  it('should reject when open_id does not match', async () => {
    mockRequest.mockResolvedValue({
      code: 0,
      data: {
        access_token: 'u-access-token',
        refresh_token: 'u-refresh-token',
        expires_in: 7200,
        open_id: 'ou_different_user',
      },
    });

    const url = generateAuthUrl('ou_user123', 'oc_chat456');
    const state = new URL(url).searchParams.get('state')!;
    const result = await handleOAuthCallback('valid_code', state);

    expect(result).toContain('授权用户与发起用户不一致');
    expect(mockUpsertUserToken).not.toHaveBeenCalled();
  });

  it('should handle API error', async () => {
    mockRequest.mockResolvedValue({ code: 10003, msg: 'invalid code' });

    const url = generateAuthUrl('ou_user123', 'oc_chat456');
    const state = new URL(url).searchParams.get('state')!;
    const result = await handleOAuthCallback('bad_code', state);

    expect(result).toContain('授权失败');
    expect(mockUpsertUserToken).not.toHaveBeenCalled();
  });
});

describe('getValidUserToken', () => {
  it('should return undefined when no token stored', async () => {
    mockGetUserToken.mockReturnValue(undefined);
    const token = await getValidUserToken('ou_user123');
    expect(token).toBeUndefined();
  });

  it('should return access token when not expired', async () => {
    mockGetUserToken.mockReturnValue({
      accessToken: 'u-valid-token',
      refreshToken: 'u-refresh-token',
      tokenExpiry: Math.floor(Date.now() / 1000) + 3600, // 1 hour from now
    });
    const token = await getValidUserToken('ou_user123');
    expect(token).toBe('u-valid-token');
    expect(mockRequest).not.toHaveBeenCalled(); // no refresh needed
  });

  it('should refresh token when expired', async () => {
    mockGetUserToken.mockReturnValue({
      accessToken: 'u-expired-token',
      refreshToken: 'u-refresh-token',
      tokenExpiry: Math.floor(Date.now() / 1000) - 100, // already expired
    });
    mockRequest.mockResolvedValue({
      code: 0,
      data: {
        access_token: 'u-new-token',
        refresh_token: 'u-new-refresh',
        expires_in: 7200,
      },
    });

    const token = await getValidUserToken('ou_user123');
    expect(token).toBe('u-new-token');
    expect(mockRequest).toHaveBeenCalledWith(expect.objectContaining({
      url: '/open-apis/authen/v1/oidc/refresh_access_token',
    }));
    expect(mockUpsertUserToken).toHaveBeenCalledWith(
      'ou_user123',
      'u-new-token',
      'u-new-refresh',
      expect.any(Number),
    );
  });

  it('should delete token when refresh fails', async () => {
    mockGetUserToken.mockReturnValue({
      accessToken: 'u-expired-token',
      refreshToken: 'u-refresh-token',
      tokenExpiry: Math.floor(Date.now() / 1000) - 100,
    });
    mockRequest.mockRejectedValue(new Error('refresh failed'));

    const token = await getValidUserToken('ou_user123');
    expect(token).toBeUndefined();
    expect(mockDeleteUserToken).toHaveBeenCalledWith('ou_user123');
  });

  it('should refresh token when about to expire (within 5 min buffer)', async () => {
    mockGetUserToken.mockReturnValue({
      accessToken: 'u-about-to-expire',
      refreshToken: 'u-refresh-token',
      tokenExpiry: Math.floor(Date.now() / 1000) + 100, // less than 5 min buffer
    });
    mockRequest.mockResolvedValue({
      code: 0,
      data: {
        access_token: 'u-refreshed-token',
        refresh_token: 'u-new-refresh',
        expires_in: 7200,
      },
    });

    const token = await getValidUserToken('ou_user123');
    expect(token).toBe('u-refreshed-token');
  });
});
